-- 1. Tabla de CIUDADANOS
CREATE TABLE CIUDADANOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    NIF VARCHAR2(20)
);

-- 2. Tabla de INMUEBLES
CREATE TABLE INMUEBLES (
    ID NUMBER PRIMARY KEY,
    CIUDADANO_ID NUMBER,
    DIRECCION VARCHAR2(200),
    VALOR_CATASTRAL NUMBER(10, 2),
    METROS_CUADRADOS NUMBER,
    ZONA VARCHAR2(50), -- 'CENTRO', 'PERIFERIA'
    CONSTRAINT fk_ciudadano FOREIGN KEY (CIUDADANO_ID) REFERENCES CIUDADANOS(ID)
);

-- 3. Tabla de NOTIFICACIONES
CREATE TABLE NOTIFICACIONES (
    ID NUMBER PRIMARY KEY,
    CIUDADANO_ID NUMBER,
    MENSAJE VARCHAR2(500),
    FECHA_ENVIO DATE,
    ESTADO VARCHAR2(20) -- 'PENDIENTE', 'ENVIADA'
);

-- 4. Secuencia para IDs
CREATE SEQUENCE SEQ_NOTIF START WITH 1 INCREMENT BY 1;

-- 5. Datos de Prueba
INSERT INTO CIUDADANOS (ID, NOMBRE, NIF) VALUES (1, 'Juan Perez', '12345678A');

INSERT INTO INMUEBLES (ID, CIUDADANO_ID, DIRECCION, VALOR_CATASTRAL, METROS_CUADRADOS, ZONA) 
VALUES (101, 1, 'Calle Mayor 1', 0, 90, 'CENTRO');

COMMIT;